src/Entity/Category.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CategoryRepository")
 */
class Category
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $name;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $description;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_of_creation;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_of_last_modification;

    /**
     * @ORM\ManyToMany(targetEntity="App\Entity\Product", mappedBy="categories")
     */
    private $products;

    public function __construct()
    {
        $this->products = new ArrayCollection();
    }

    public function getId()
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getDateOfCreation(): ?\DateTimeInterface
    {
        return $this->date_of_creation;
    }

    public function setDateOfCreation(\DateTimeInterface $date_of_creation): self
    {
        $this->date_of_creation = $date_of_creation;

        return $this;
    }

    public function getDateOfLastModification(): ?\DateTimeInterface
    {
        return $this->date_of_last_modification;
    }

    public function setDateOfLastModification(\DateTimeInterface $date_of_last_modification): self
    {
        $this->date_of_last_modification = $date_of_last_modification;

        return $this;
    }

    /**
     * @return Collection|Product[]
     */
    public function getProducts(): Collection
    {
        return $this->products;
    }

    public function addProduct(Product $product): self
    {
        if (!$this->products->contains($product)) {
            $this->products[] = $product;
            $product->addCategory($this);
        }

        return $this;
    }

    public function removeProduct(Product $product): self
    {
        if ($this->products->contains($product)) {
            $this->products->removeElement($product);
            $product->removeCategory($this);
        }

        return $this;
    }
}

src/Form/CategoryType.php
<?php

namespace App\Form;

use App\Entity\Category;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CategoryType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('name', TextType::class, ['attr' => ['class' => 'form-control']])
            ->add('description', TextType::class, ['attr' => ['class' => 'form-control']])
        ;
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Category::class,
        ]);
    }
}

src/Controller/CategoryController.php
<?php

namespace App\Controller;

use App\Entity\Category;
use App\Form\CategoryType;
use App\Repository\CategoryRepository;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/category")
 */
class CategoryController extends Controller
{
    /**
     * @Route("/", name="category_index", methods="GET")
     */
    public function index(CategoryRepository $categoryRepository): Response
    {
        return $this->render('category/index.html.twig', ['categories' => $categoryRepository->findAll()]);
    }

    /**
     * @Route("/new", name="category_new", methods="GET|POST")
     */
    public function new(Request $request): Response
    {
        $category = new Category();
        $this->denyAccessUnlessGranted('create', $category);
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();
            $category->setDateOfCreation(new \DateTime('now'));
            $category->setDateOfLastModification(new \DateTime('now'));
            $em->persist($category);
            $em->flush();
            if (null != $category->getId()) {
                $this->addFlash('success', 'Category added successfuly');
            } else {
                $this->addFlash('error', 'Category not added to database');
            }

            return $this->redirectToRoute('category_index');
        }

        return $this->render('category/new.html.twig', [
            'category' => $category,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="category_show", methods="GET")
     */
    public function show(Category $category): Response
    {
        $this->denyAccessUnlessGranted('view', $category);
        return $this->render('category/show.html.twig', ['category' => $category]);
    }

    /**
     * @Route("/{id}/edit", name="category_edit", methods="GET|POST")
     */
    public function edit(Request $request, Category $category): Response
    {
        $this->denyAccessUnlessGranted('edit', $category);
        $form = $this->createForm(CategoryType::class, $category);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $category->setDateOfLastModification(new \DateTime('now'));
            $this->getDoctrine()->getManager()->flush();
            if (null != $category->getId()) {
                $this->addFlash('success', 'Category updated successfuly');
            } else {
                $this->addFlash('error', 'Category not updated to database');
            }

            return $this->redirectToRoute('category_edit', ['id' => $category->getId()]);
        }

        return $this->render('category/edit.html.twig', [
            'category' => $category,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="category_delete", methods="DELETE")
     */
    public function delete(Request $request, Category $category): Response
    {
        $this->denyAccessUnlessGranted('delete', $category);
        if ($this->isCsrfTokenValid('delete'.$category->getId(), $request->request->get('_token'))) {
            $em = $this->getDoctrine()->getManager();
            $em->remove($category);
            $em->flush();
            if (null != $category->getId()) {
                $this->addFlash('error', 'Category not deleted');
            }  else {
                $this->addFlash('success', 'Category deleted successfuly');
            }
        }

        return $this->redirectToRoute('category_index');
    }

    public function renderCategories(): Response
    {
        $categories = $this->getDoctrine()->getRepository(Category::class)->findAll();
        return $this->render('includes/menu.html.twig', ['categories' => $categories]);
    }
}

templates/category/_delete_form.html.twig
<form method="post" action="{{ path('category_delete', {'id': category.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_method" value="DELETE">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ category.id) }}">
    <button class="btn btn-danger mt-2">Delete</button>
</form>

templates/category/_form.html.twig
{{ form_start(form, {attr: {class: 'form-group w-75'} }) }}
    {{ form_widget(form) }}
    <button class="btn btn-primary mt-2">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/category/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit {{ category.getName() }}{% endblock %}

{% block body %}
    <h1 class="my-3">Edit {{ category.getName() }}</h1>

    {{ include('category/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('category_index') }}">back to list</a>

    {{ include('category/_delete_form.html.twig') }}
{% endblock %}

templates/category/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Categories{% endblock %}

{% block body %}
    <h1 class="my-4">Categories</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>Name</th>
                <th>Description</th>
                <th>Date_of_creation</th>
                <th>Date_of_modification</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for category in categories %}
            <tr>
                <td>{{ category.id }}</td>
                <td>{{ category.name }}</td>
                <td>{{ category.description }}</td>
                <td>{{ category.dateOfCreation ? category.dateOfCreation|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ category.dateOfLastModification ? category.dateOfLastModification|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a class="btn btn-outline-primary" href="{{ path('category_show', {'id': category.id}) }}">show</a>
                    <a class="btn btn-outline-secondary" href="{{ path('category_edit', {'id': category.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="6">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a class="btn btn-primary" href="{{ path('category_new') }}">Create new</a>
    <a class="btn btn-info" href="{{ path('product_index') }}">Products</a>
{% endblock %}

templates/category/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Category{% endblock %}

{% block body %}
    <h1>Create new Category</h1>

    {{ include('category/_form.html.twig') }}

    <a href="{{ path('category_index') }}">back to list</a>
{% endblock %}

templates/category/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ category.getName() }}{% endblock %}

{% block body %}
    <h1 class="my-3">{{ category.getName() }}</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ category.id }}</td>
            </tr>
            <tr>
                <th>Name</th>
                <td>{{ category.name }}</td>
            </tr>
            <tr>
                <th>Description</th>
                <td>{{ category.description }}</td>
            </tr>
            <tr>
                <th>Date_of_creation</th>
                <td>{{ category.dateOfCreation ? category.dateOfCreation|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Date_of_modification</th>
                <td>{{ category.dateOfLastModification ? category.dateOfLastModification|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('category_index') }}">back to list</a>

    <a class="btn btn-info" href="{{ path('category_edit', {'id': category.id}) }}">edit</a>

    {{ include('category/_delete_form.html.twig') }}

    {% if category.getProducts().isEmpty() %}
        <p>No products</p>
    {% else %}
        <p class="mt-4">Products: </p>
        <ul class="list-group w-25 mb-4">
            {% for product in category.getProducts() %}
                <li class="list-group-item">
                    <a href="{{ path('product_show', {'id': product.id}) }}">{{ product.getName() }}</a>
                    <img class="img-thumbnail img-fluid" width="100" src="{{ product.getMainImage() }}" alt="">
                </li>
            {% endfor %}
        </ul>
    {% endif %}

{% endblock %}